name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install flask==2.3.3

      - name: Test Flask Import
        run: |
          python -c "from flask import Flask; print('Flask imported successfully')"

  deploy:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Create Deployment Package
        run: |
          zip -r deployment.zip .

      - name: Upload to S3
        run: |
          aws s3 cp deployment.zip s3://devops-bucket-569038358773/deployment.zip

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceIds,Values=i-0ac1da3155c2d525b" \
          --parameters commands="echo Deployment executed successfully" \
          --region us-east-1
